### ISSUE TITLE
App shows up, but when i click it, I get no response

### ISSUE THREAD

**Issue by Christoffer-M** [andriy921/Simple-Twitch#5]
Hi there, I really hope there is a solution to my problem cause i would really like it to work! 

So i did as instructed and plugged in my USB, turned my TV on/off and the twitch app shows up on the app screen but when i click it, nothing happens? Is this a known issue or?

Hope you can help :)

**Comment by Christoffer-M** [comment]
Oh nvm, now it works  lol. Not sure what i did different! :D Works amazing, thank you so much!

**Comment by astashko** [comment]
It looks like you need to be logged in to the store in order to open the app. So first time running the app after turning on tv is always slow, since it authorizes to the store in background. If you have some troubles with connection app would also won't open.
Other known bug of lg tvs is - you can not automatically login to store if you careated lg account on top of facebook account. If that's the case, then most likely you'll have to open lg store app, then open my app every time you turn off your TV.

**Comment by Christoffer-M** [comment]
Yea, i just made an LG store account and after that it worked, so that must have been the problem! The App works great btw, I really love it! Would be even better if i could choose what video quality I wanted, but other than that its amazing!
